"""
digit_preprocessing.py  (auto-generated by Notebook 1)

Shared OpenCV preprocessing for handwritten-digit recognition.
Used IDENTICALLY at training time (Notebook 2) and at inference/deployment time
to eliminate train/serve skew.
"""
import cv2
import numpy as np
from scipy import ndimage


def to_grayscale(image):
    if isinstance(image, str):
        image = cv2.imread(image, cv2.IMREAD_GRAYSCALE)
        if image is None:
            raise FileNotFoundError('Could not read image from the given path.')
        return image
    if image.ndim == 3:
        return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return image


def binarize(image, method='otsu', blur=True):
    gray = to_grayscale(image)
    if blur:
        gray = cv2.GaussianBlur(gray, (3, 3), 0)
    if method == 'adaptive':
        binary = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                       cv2.THRESH_BINARY, 31, 10)
    else:
        _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    if np.mean(binary) > 127:
        binary = cv2.bitwise_not(binary)
    return binary


def deskew(img, size=None):
    h, w = img.shape[:2]
    size = size or w
    m = cv2.moments(img)
    if abs(m['mu02']) < 1e-2:
        return img.copy()
    skew = m['mu11'] / m['mu02']
    M = np.float32([[1, skew, -0.5 * size * skew], [0, 1, 0]])
    return cv2.warpAffine(img, M, (size, size),
                          flags=cv2.WARP_INVERSE_MAP | cv2.INTER_LINEAR)


def _shift_to_center_of_mass(img):
    cy, cx = ndimage.center_of_mass(img)
    rows, cols = img.shape
    shiftx = np.round(cols / 2.0 - cx).astype(int)
    shifty = np.round(rows / 2.0 - cy).astype(int)
    M = np.float32([[1, 0, shiftx], [0, 1, shifty]])
    return cv2.warpAffine(img, M, (cols, rows))


def center_and_resize(binary, out_size=28, box=20):
    coords = cv2.findNonZero(binary)
    if coords is None:
        return np.zeros((out_size, out_size), dtype=np.uint8)
    x, y, w, h = cv2.boundingRect(coords)
    digit = binary[y:y + h, x:x + w]
    if w > h:
        new_w, new_h = box, max(1, int(round(h * box / w)))
    else:
        new_h, new_w = box, max(1, int(round(w * box / h)))
    digit = cv2.resize(digit, (new_w, new_h), interpolation=cv2.INTER_AREA)
    canvas = np.zeros((out_size, out_size), dtype=np.uint8)
    x0 = (out_size - new_w) // 2
    y0 = (out_size - new_h) // 2
    canvas[y0:y0 + new_h, x0:x0 + new_w] = digit
    return _shift_to_center_of_mass(canvas)


def preprocess_digit(image, do_deskew=True, out_size=28, flatten=False, normalize=False):
    binary = binarize(image)
    if do_deskew:
        binary = deskew(binary)
    tile = center_and_resize(binary, out_size=out_size)
    if normalize:
        tile = tile.astype(np.float32) / 255.0
    if flatten:
        return tile.reshape(-1)
    return tile


def segment_digits(image, min_area=80, pad_ratio=0.25, merge_kernel=1,
                   max_aspect=1.1, split_wide=True):
    """Locate individual digits and return (tiles, boxes) sorted left-to-right.

    Key fixes for "two digits captured as one":
      - merge_kernel defaults to 1 (NO dilation) so close digits stay separate.
        Dilation was bridging neighbouring strokes into a single blob.
      - Any contour wider than `max_aspect * height` is assumed to contain
        multiple touching digits and is split evenly into round(w / digit_w)
        columns (a digit is roughly as wide as it is tall).
    """
    binary = binarize(image)

    # Only dilate if explicitly asked (helps re-join a single BROKEN digit, but
    # also risks merging neighbours — off by default).
    if merge_kernel and merge_kernel > 1:
        kernel = np.ones((merge_kernel, merge_kernel), np.uint8)
        search = cv2.dilate(binary, kernel, iterations=1)
    else:
        search = binary

    contours, _ = cv2.findContours(search, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    boxes = []
    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        if w * h < min_area or h < 10:
            continue

        # A single digit is ~0.6*h wide. If a box is much wider than tall, it
        # most likely holds several touching digits -> split it into columns.
        if split_wide and w > max_aspect * h:
            n = max(1, int(round(w / (0.6 * h))))   # estimated digit count
            step = w / n
            for k in range(n):
                boxes.append((int(x + k * step), y, int(np.ceil(step)), h))
        else:
            boxes.append((x, y, w, h))

    # Read order = left to right (add y as a tiebreak for multi-row pages).
    boxes.sort(key=lambda b: (b[0]))

    tiles = []
    for (x, y, w, h) in boxes:
        pad = int(pad_ratio * max(w, h))
        x0, y0 = max(0, x - pad), max(0, y - pad)
        x1, y1 = min(binary.shape[1], x + w + pad), min(binary.shape[0], y + h + pad)
        crop = binary[y0:y1, x0:x1]
        tiles.append(preprocess_digit(crop, do_deskew=True))
    return tiles, boxes
